### PR TITLE
Feature: Data Download

### PR DESCRIPTION
**Pull request by maxmalynowsky**
Adds two modules for assessing COD-AB quality:
- metadata: generates a spreadsheet at `data/metadata.csv` listing information that can be accessed from the ITOS ArcGIS server without downloading layers themselves.
- download: using the metadata sheet, iterates through the list to download every available layer.

Other changes:
- Remove black / isort in favour of [ruff](https://docs.astral.sh/ruff/) for linting and formatting.
- Add docker container able to run all commands through `docker compose up`.

### CODE REVIEW

**Comment by vshlemon** [comment]
Hi Max, am testing this out - will take some time to understand fully what's going on/how to refactor etc.

But currently the `src/metadata/__main__/save_metadata()` function does not work as it tries to save to the working directory of the docker container in a directory that doesn't exist (I also believe it is not reading the `../..` syntax as you intended) - so you might want to create the directory in case it doesn't exist, and also perhaps use `pathlib` to get the parent folders - https://stackoverflow.com/questions/54401973/pythons-pathlib-get-parents-relative-path.

Hope this works well then I can try the download step. 

We probably want to think about whether the best place to put the output is in the docker container as then we'd need a way to get it back to the user's local machine I am guessing - perhaps using `subprocess` & `docker cp`. But I do think if possible converting to a non-docker approach, if not infeasible, would be most desirable but have to weigh up time/effort/reliability/use-case etc.

**Comment by vshlemon** [comment]
Trying to test out the httpx.download option using just poetry & no docker. Got the following error, I believe it originates in the way the Path is stated here - `cod-ab-data-quality/src/download/__init__.py`

image

**Comment by maxmalynowsky** [comment]
> Trying to test out the httpx.download option using just poetry & no docker. Got the following error, I believe it originates in the way the Path is stated here - `cod-ab-data-quality/src/download/__init__.py`

Not likely, otherwise `src.metadata` would have failed since it sets Path in the exact same way. What I think might be happening is that when you ran the command with Docker, there's a `mkdir` that created the download directory if it doesn't exist. It looks like there's a permission error accessing that folder from when it was created with Docker under WSL and then accessed by Windows. I restructured the `data` directory to add the folder boundaries are downloaded to into GitHub which should prevent that error.

**Comment by maxmalynowsky** [comment]
> Thanks Max - it seems ready to merge, but it takes a while as it downloads everything each time. I imagine sometimes this might not be desired so an option at the CLI for `overwrite` & `output` locations would be handy. My comments for the CLI features are below - I can either close this branch (merge) & open an issue to implement them or if you'd prefer to I can leave the branch open if you wanted to implement them? I am happy either way, would be good for me to implement to get more familiar but cool if you want to.

Thanks a lot for battle testing this, you've given a lot of super useful feedback, downloading is the hardest part since it deals with things outside of our control. I think we should merge now, otherwise this runs the risk of turning into a forever branch.

On the things you brought up:
- I don't think you can pass arguments to a `make` rule, for example `make run --ISO3=MDG`?
- This could be an option, but I wouldn't have this as the default behaviour. There's no way of knowing if the data you've already downloaded has a newer version available from the ArcGIS server without downloading it. My thinking was that you would use the `ISO3` environment variable to run the pipeline for just a subset of locations. I was also thinking that downloading and running checks could be separate, users could add their own data to `data/boundaries` and skip `make metadata` / `make download`.
- For this, do you mean allow users to point to a different URL to get data from, and uploading to cloud storage? There has been interest from the Centre for Humanitarian Data in creating a new HDX dataset with all 525 current CODs in one easy to download zip file, something this tool could support.

**Comment by vshlemon** [comment]
Ok am merging now - will open up the download options as issues as I think it would be useful to include.

I meant adding arguments to the module execution via. an argparser. I wasn't envisioning `make` as the main point of entry for everyone, but it could keep the default args for module execution.

Yep, not as default, just for flexibility.

And I meant more for where you download to in case you didn't want to save locally. But that could come later if there's a need. And adding an argparser would enable for different sources to download from as well (or methods) so that would be good.

This is really great stuff, Thanks for your patience with me testing it out as well :)

**Pull request merged**
