### PR TITLE
Suggested structure for data quality entrypoints

### PR DESCRIPTION
**Pull request by maxmalynowsky**
As this project grows in complexity, managing work in parallel can become a challenge. This pull commit suggests the following structure for organization:

1. Separating the codebase into 4 sub-modules (`metadata`, `download`, `checks`, `scores`), each depending on the outputs of the previous. `metadata` generates a table used for iterating through the 164 locations, `download` fetches the boundary data from ITOS, `checks` generates an additional table with summaries about the datasets, and finally `scores` builds up the final output table that will be delivered to ITOS.
2. For `checks`, each type of check can be complicated, with features such as spatial coverage requiring level(n) vs level(n-1) comparisons. Additionally, it's not optimal for each check to do its own file I/O against boundary data. The following is suggested to optimize performance / memory:
    - Create an iterable with each item containing the following `(check_function, results_list)`
    - Iterate through ISO3 values, creating a list of GeoDataFrames containing admin levels 0-n.
    - Iterate through the check functions, passing to them the results list for that check as well as boundary data needed for checking.
    - When all checks have run against the ISO3's GeoDataFrames, they are released from memory and a new ISO3 is loaded in.
    - After all the checks have been performed for all ISO3 values, join the check tables together by ISO3 and admin level.
    - Output the final result as a single table: `data/tables/checks.csv`.
    - Example of checks table output: [checks.csv](https://github.com/user-attachments/files/16657978/checks.csv)
3. For `scores`, the structure should be much simpler than the above. Pandas alone should be enough to generate new score columns from the results of the checks, as well as calculating the final composite score. While the checks table is disaggregated by both ISO3 and admin level, the final score table will probably be aggregated by ISO3 only.

### CODE REVIEW

**Comment by vshlemon** [comment]
I like @maxmalynowsky idea. I would suggest we have an input and output schema for each of the modules so we can know what to expect explicitly & can import that schema to type hint against in functions downstream.

I might suggest loose duck typing using protocol classes so schemas can be extended without downstream failures, and then maintainer of each module can update to utilise new attributes of schema as needed? Could also use Pydantic classes for basic validation of what's downloaded?

I am still unclear on which formats we can expect users to try using the tool with though - @maxmalynowsky any thoughts since ITOS is the user as to the priority of formats to adapt to? As there might need to be another module 'conversion' for going from that format to the one tests are written in?

@Murray2015 & @maxmalynowsky if there are any tasks I can do let me know, or I can just support like this

**Comment by maxmalynowsky** [comment]
I'm not sure I know exactly what you have in mind with schemas or duck typing. While some of the checks are looking for the existence of certain columns, there are many more that will be going into the substance like checking for Latin characters.

As for contributing, my thinking was the following:
- `checks`: modules here help to aggregate data later used for scoring. There is no ranking or prioritization done here, just taking the source data and summarizing it in a more useful format. Here are two examples that help make this [checks table](https://github.com/user-attachments/files/16671137/checks.csv):
    - `dates`: https://github.com/mapaction/cod-ab-data-quality/blob/feature/entry-point/src/checks/dates.py
    - `languages`: https://github.com/mapaction/cod-ab-data-quality/blob/feature/entry-point/src/checks/languages.py
    - Further modules could be added here by yourself from Features 2.2.1 to 2.2.7.
- `scores`: once enough data has been summarized by the checks, we would have to creates tests here which output some kind of assessment score from 0-1. These are the sections described by Features 2.3.1 to 2.3.7.
    - I haven't elaborated on what that might look like in this pull request yet, but I'm guessing it could be broken down into sub-modules like scoring for dates and languages as done above.

**Comment by maxmalynowsky** [comment]
Hmm, since we're dealing with messy, incomplete, or missing data, I don't know how far a schema will get us. There are about 200 different field names we can expect from any given dataset, which we'd use regex to check against according to the outline document. The field types are easy, they're all going to be string except for the two date columns (date, validOn).

It's true that none of the modules return anything. It's been my experience that having intermediate outputs are extremely helpful for debugging complex data like the kind we have. For the downloaded boundaries, there are currently 527 files taking up 4.74 GB as binaries. Loading them all into memory at once would probably take up a few hundred GB. These are the current assumptions between modules, which could be made into a comment somewhere:
- module: `metadata`
    - depends: none
    - outputs: `data/tables/metadata.csv`
- module: `download`
    - depends: `data/tables/metadata.csv`
    - outputs: `data/boundaries/*.gpkg`
- module: `checks`
    - depends: `data/tables/metadata.csv`, `data/boundaries/*.gpkg`
    - outputs: `data/tables/checks.csv`
- module: `scores`
    - depends: `data/tables/checks.csv`
    - outputs: `data/tables/scores.csv`

**Review by ediakatos — COMMENTED** [review]
Hi Team,

I have successfully built and ran the container ( although I haven't reviewed the whole codebase ). The branch appears to be a working branch with additional functionality built on top of the previous main branch, and it looks good to merge.

However, I have a couple of questions regarding the two Pull requests ( #4 and #7 ):
1. Are the unit tests in this branch intended to replace the ones that Murray was working on?
2. What is the strategy for integrating these unit tests, considering there seem to be two workflows: one focusing on building functionality and the other on testing?

Best,
Evangelos

**Comment by ediakatos** [comment]
Thank you for the clarification @maxmalynowsky

**Review by ediakatos — COMMENTED** [review]
While running the project, I encountered the following error: 

```bash
68%|██████▊   | 358/527 [1:43:58<49:04, 17.43s/it, PHL_ADM1]    
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/src/download/ogr2ogr.py", line 117, in download
    raise RuntimeError(filename)
RuntimeError: phl_adm1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/app/src/__main__.py", line 18, in <module>
    main()
  File "/usr/src/app/src/__main__.py", line 12, in main
    download()
  File "/usr/src/app/src/download/__main__.py", line 38, in main
    download(iso3, lvl, idx, row["itos_url"])
  File "/usr/src/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x779b97023fe0 state=finished raised RuntimeError>]
make: *** [Makefile:45: run] Error 1
```
It seems that is failing to download ***phl_adm1*** , and despite retrying it raises a ***RetryError*** .

**Comment by maxmalynowsky** [comment]
`PHL_ADM1` is the layer with the single largest individual geometries, so even if it is downloaded with server pagination going 1 feature at a time, if the server is under high loads and has limited memory, this is the layer that would cause it to fail. What you're seeing is that the function has attempted the download 5 times already, which is the maximum number of retries I've given to tenacity, so it gives the RetryError you see above.

**Comment by ediakatos** [comment]
Thanks for the clarification @maxmalynowsky!

**Comment by maxmalynowsky** [comment]
I'm seeing a lot of `503 Service Unavailable` responses coming from the ITOS ArcGIS server right now. Unfortunately the only solution in cases like this is to wait a few hours and try again later when fewer people are attempting to access the server.

**Comment by vshlemon** [comment]
I am also getting some issues, it just gets stuck on the metadata step. Given @ediakatos issues it might be worth implementing some mechanism that skips over known exceptions and just logs them instead of interrupting execution? Also might be helpful to put some more logging in to capture known issues and inform the user. I assume my issue is happening in the `get_metadata()` function during the http call or the `get_iso3()` call to collect from `.env`. Probably helpful for the user to have a running log of what's going on to troubleshoot. Also relying on them to rename `env.example` as an execution step might be tricky - could we not refactor to use argparser to pass in specific iso codes if they wanted?

image

**Comment by vshlemon** [comment]
I think adding argparser entry points to each module would help. For example if I want to test the checks module on just a single file then I have no option for that right now I don't think. And if I wanted to test download module on a single iso, for now I dont think I could as the pipeline execution is all wrapped up into one process - I'd kind of want to be able to run download module on one iso which then triggered the metadata module for the same iso - which would need their entry `main` functions to take some arguments as well.

**Comment by maxmalynowsky** [comment]
There aren't any known exceptions right now, I've run the `metadata` and `download` functions overnight about a half dozen times already and they usually always work. The few times they don't are like today when there are server errors on the ITOS side, that's something we have no control over. The metadata check should take under 5 min in ideal conditions, but if the server is under heavy loads and is timing out regularly, that could extend up to 30 min or more. Same for downloads, in ideal conditions all 527 datasets should take under 2 hours, but it has been as long as 4 hours for me sometimes. It's possible to improve the logging around that, but there's nothing really actionable that can be done other than waiting to try again later.

Since the only planned output to ITOS is a table, I've designed things so far as a pipeline intended to be executed in the cloud on a regular basis so that they doesn't have to concern themselves with that. For us as developers, I've tried to make things as easy as possible by making things like `.env` files optional. If you wanted to run the entire pipeline for just a single location, setting something like `ISO3=PHL` applies to `metadata`, `download`, `checks`, and `score`, so you can already do things like testing the download module on a single ISO. But given the network issues potentially involved with `metadata` and `downloads`, I wouldn't run those in development more than is necessary. The argparser comment makes sense, I could add that in to this branch along with the docstrings I was planning.

**Comment by maxmalynowsky** [comment]
Argparsing and docstring comments are all in, ready to have this branch formally reviewed and merged if it looks good to everyone!

**Comment by vshlemon** [comment]
Ok, I've tested on a single iso code so happy to merge.

Looks good @maxmalynowsky. I won't be able to attend the next meeting. I still think it would be useful to have more design to represent a more generic check function/class that others depend on, have a read in function that stitches download files from multiple layers into a single type per iso, more explicit passing of information between modules and flexibility for executing independently (argparser interface per module & each module triggering the ones preceding it), more running commentary of what's happening during the process for the user's comfort (the loading bars are excellent). 

I think these things would help to communicate about the project and have a clear design to onboard people into and read the codebase (e.g. if a new check is to be added you can point them towards inheriting from a class or writing one which matches a protocol - so they know what input they can expect and what they must return, and what methods to fill out for it).

**Review by vshlemon — APPROVED** [review]

**Comment by Murray2015** [comment]
I'm sorry for not participating in this discussion; I was in the Lake District on AL all week (summary: tons of rain!). I think the suggested structure is good. @vshlemon, I think I get what you're suggesting with 🦆 typing and protocols, but it'd be good to see a PR with exactly what you mean 🙂

**Pull request merged**
